language: cpp
dist: trusty
os: linux
addons:
         apt:
                sources:
                        - ubuntu-toolchain-r-test
                packages:
                        - g++-7
script:
        - g++ main.cpp -o main -Wall -Wextra -Werror -Wpedantic -o2 
after_success:
        - echo "success"

after_failure:
        - echo "failure" 
